### ISSUE TITLE
Lightbox Gallery v1.12.0 Evoq 8.4.2 - Edit New Album doesn't work

### ISSUE THREAD

**Issue by JaySMa** [WillStrohl/dnnextensions#129]
Added a new album and this worked fine and album was created; modal pop-ups appear to be working properly.  But, there isn't a close button and no way to close the modal pop-up.

Went in to edit the album and recieved the error below:

**Use this form to add a new album, or to update an existing one.**

**Error: is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object. at WillStrohl.Modules.Lightbox.EditLightbox.BindData() at WillStrohl.Modules.Lightbox.EditLightbox.Page_Load(Object sender, EventArgs e) --- End of inner exception stack trace ---**

**_Event Logs:_**
ModuleId:11470
ModuleDefId:202
FriendlyName:
ModuleControlSource:DesktopModules/WillStrohl.LightBoxGallery/EditLightbox.ascx
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:becb105c-4b68-4d8f-ac9c-9ac70a4b1c56
AssemblyVersion:8.4.2
PortalId:18
UserId:1
TabId:3066
RawUrl:/Photoalbum/ctl/Edit/mid/11470/AlbumId/12
Referrer:http://dnntesturl/Photoalbum
UserAgent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.87 Safari/537.36 OPR/37.0.2178.41
ExceptionHash:QZQDRqMsoj3lg/2VQ8CUgg==
Message:Object reference not set to an instance of an object.
StackTrace:
InnerMessage:Object reference not set to an instance of an object.
InnerStackTrace:
   at WillStrohl.Modules.Lightbox.EditLightbox.BindData()
   at WillStrohl.Modules.Lightbox.EditLightbox.Page_Load(Object sender, EventArgs e)
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:

**Comment by JaySMa** [comment]
I also opened issue #130; but what's odd is that I'm able to open an album which was created with the version prior.  Editing an previously created album works fine.

**Comment by hismightiness** [comment]
Unfortunately, we have no way to test, view, duplicate, or otherwise troubleshoot anything related to Evoq.  This module appears to work fine on DNN Platform 8.0.3 and doesn't exhibit the issues you just described.

In order for me to be able to perform any work on this, I'm going to need for you to provider some deeper troubleshooting details about any client-side issues, and using the debugging symbols for any server-side errors you find.  I've updated the release to include the required debug symbols.

https://github.com/hismightiness/dnnextensions/releases/tag/Lightbox-01.12.00

If you need assistance on how to apply the debug symbols and report the detailed error, you can use this article:

https://hotcakescommerce.zendesk.com/hc/en-us/articles/205426505-How-to-Get-Detailed-Error-Reports

Also, when reporting any bugs, this would be the most useful way to have them reported.

https://github.com/hismightiness/dnnextensions/wiki/Create-Issues-or-Ideas

**Comment by WillStrohl** [comment]
Unable to duplicate this issue in [the latest release](https://github.com/WillStrohl/dnnextensions/releases/tag/LBGallery-01.15.00).
